// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <C:/Users/Mehrdad/source/repos/CryEngineInPractice/Code/Components/Player.cpp>
#include <C:/Users/Mehrdad/source/repos/CryEngineInPractice/Code/Components/SpawnPoint.cpp>

